# Form implementation generated from reading ui file 'c:\Users\jonat\Desktop\Proyectos Python\Fichaje_Empleados\screens_ui\SettingsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(314, 435)
        MainWindow.setStyleSheet("background-color: #afdce4;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 80, 91, 16))
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 140, 101, 16))
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 200, 121, 16))
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 250, 121, 16))
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 300, 131, 16))
        self.label_5.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.lblNombre = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNombre.setGeometry(QtCore.QRect(50, 100, 211, 31))
        self.lblNombre.setStyleSheet("background-color: #d9d9d9;\n"
"border-radius: 6px;\n"
"padding: 5px;")
        self.lblNombre.setText("")
        self.lblNombre.setObjectName("lblNombre")
        self.btnConfirmar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConfirmar.setGeometry(QtCore.QRect(110, 380, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.btnConfirmar.setFont(font)
        self.btnConfirmar.setStyleSheet("background-color: #d9d9d9;\n"
"border-radius: 6px;\n"
"padding: 5px;\n"
"")
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.lblUsuario = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblUsuario.setGeometry(QtCore.QRect(50, 160, 211, 31))
        self.lblUsuario.setStyleSheet("background-color: #d9d9d9;\n"
"border-radius: 6px;\n"
"padding: 5px;")
        self.lblUsuario.setText("")
        self.lblUsuario.setObjectName("lblUsuario")
        self.txtContrasenaActual = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtContrasenaActual.setGeometry(QtCore.QRect(50, 220, 211, 31))
        self.txtContrasenaActual.setStyleSheet("background-color: white;\n"
"border-radius: 6px;\n"
"padding: 5px;")
        self.txtContrasenaActual.setObjectName("txtContrasenaActual")
        self.txtNuevaContrasena = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNuevaContrasena.setGeometry(QtCore.QRect(50, 270, 211, 31))
        self.txtNuevaContrasena.setStyleSheet("background-color: white;\n"
"border-radius: 6px;\n"
"padding: 5px;")
        self.txtNuevaContrasena.setObjectName("txtNuevaContrasena")
        self.txtConfirmarContrasena = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtConfirmarContrasena.setGeometry(QtCore.QRect(50, 320, 211, 31))
        self.txtConfirmarContrasena.setStyleSheet("background-color: white;\n"
"border-radius: 6px;\n"
"padding: 5px;")
        self.txtConfirmarContrasena.setObjectName("txtConfirmarContrasena")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nombre"))
        self.label_2.setText(_translate("MainWindow", "Usuario"))
        self.label_3.setText(_translate("MainWindow", "Contraseña actual"))
        self.label_4.setText(_translate("MainWindow", "Contraseña nueva"))
        self.label_5.setText(_translate("MainWindow", "Confirmar contraseña"))
        self.btnConfirmar.setText(_translate("MainWindow", "Confirmar"))
        self.label_6.setText(_translate("MainWindow", "Ajustes"))
